[package]
name = "nexispm"
version = "0.1.0"
edition = "2021"
authors = ["Kyle Gortych <kyle.gortych.dev@gmail.com>"]
description = "Declarative system package manager for NexisOS with optimized store operations, refcounting, and generation rollbacks"
license = "GPL-3.0-or-later"
repository = "https://github.com/NexisOS/NexisOS"
homepage = "https://github.com/NexisOS/NexisOS"
documentation = "https://github.com/NexisOS/NexisOS"
readme = "README.md"
keywords = ["package-manager", "linux", "declarative", "nixos-like", "rollback"]
categories = ["command-line-utilities", "development-tools", "os"]

[lib]
name = "nexispm"
path = "src/lib.rs"

[[bin]]
name = "nexis"
path = "src/main.rs"

[dependencies]
# CLI and configuration
clap = { version = "4.4", features = ["derive", "env", "color"] }
serde = { version = "1.0", features = ["derive", "rc"] }
toml = "0.8"
toml_edit = { version = "0.22", optional = true }  # Updated version
config = { version = "0.14", optional = true }
tera = { version = "1.19", optional = true }

# Validation & diagnostics
schemars = { version = "0.8", features = ["serde"] }
serde_valid = { version = "0.15", features = ["derive"] }
miette = { version = "7", features = ["fancy"] }  # Updated and added features
thiserror = "1.0"

# Storage backends - choose ONE at compile time
lmdb = { version = "0.10", features = ["sync"], optional = true }
rocksdb = { version = "0.22", features = ["multi-threaded-cf"], optional = true }


# Async runtime and HTTP client
tokio = { version = "1", features = [
    "rt-multi-thread", 
    "macros", 
    "fs", 
    "process", 
    "io-util", 
    "signal", 
    "time",
    "net"  # Added for network operations
] }
reqwest = { version = "0.12", features = ["stream", "rustls-tls", "gzip", "brotli"] }
futures = "0.3"

# Hashing and cryptography
blake3 = "1"
sha2 = "0.10"
ring = "0.17"
# Consider adding for integrity verification
ed25519-dalek = { version = "2.0", optional = true }

# Compression support
flate2 = "1.0"
tar = "0.4"
zstd = "0.13"
lz4 = { version = "1.24", optional = true }  # Fast compression option

# File system operations
walkdir = "2.5"
tempfile = "3.10"
nix = { version = "0.29", features = ["fs", "mount", "unistd"] }  # Added features for more OS ops
xattr = "1.3"
users = "0.11"
caps = { version = "0.5", optional = true }
which = "6.0"
libc = "0.2"
camino = "1.1"
fs-err = "2"
notify = "6.1"

# Error handling and logging
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Date/time handling
chrono = { version = "0.4", features = ["serde"] }

# JSON and serialization
serde_json = "1.0"
bincode = "1"

# Concurrency and performance
parking_lot = "0.12"
dashmap = "5.5"  # Concurrent HashMap
rayon = "1.10"
bloom = "0.3"

# CLI UX
console = "0.15"
indicatif = "0.17"
dialoguer = { version = "0.11", optional = true }  # Interactive prompts

# Path manipulation and glob patterns
glob = "0.3"
pathdiff = "0.2"

# Process and system info
sysinfo = { version = "0.30", optional = true }
procfs = { version = "0.16", optional = true }

# Archive handling
zip = { version = "0.6", optional = true }

[dev-dependencies]
tempfile = "3.10"
assert_fs = "1.1"
predicates = "3.1"
tokio-test = "0.4"
proptest = "1.4"   # Property-based testing

[features]
default = ["desktop-profile", "grub-integration", "validation"]

# Profiles - mutually exclusive storage backends
desktop-profile = ["lmdb-backend", "io-uring", "interactive"]
server-profile  = ["rocksdb-backend", "jemalloc", "system-info"]

# Storage backends - only one should be active
lmdb-backend = ["lmdb"]
rocksdb-backend = ["rocksdb"]  


# Integration features
grub-integration = []
selinux-support = []
systemd-integration = []
layered-config = ["config", "toml_edit"]
templating = ["tera"]
validation = ["schemars", "serde_valid", "miette/fancy"]
caps-support = ["caps"]

# Performance and system features
io-uring = ["tokio-uring"]
parallel-gc = ["rayon", "bloom", "dashmap"]
jemalloc = ["tikv-jemallocator"]
compression = ["lz4", "zip"]
crypto-verify = ["ed25519-dalek"]
interactive = ["dialoguer"]
system-info = ["sysinfo", "procfs"]

# Development and debugging
debug-store = []
extensive-logging = ["tracing-subscriber/json"]

[target.'cfg(target_os = "linux")'.dependencies]
tokio-uring = { version = "0.5", optional = true }
tikv-jemallocator = { version = "0.6", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# Ensure only one backend is selected
[package.metadata.cargo-all-features]
denylist = [
    ["lmdb-backend", "rocksdb-backend"],

    ["desktop-profile", "server-profile"]
]

# Performance optimization
[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"  # For system tools, abort on panic

[profile.dev]
debug = 2
overflow-checks = true

[profile.bench]
inherits = "release"
debug = true
