[package]
name = "nexispm"
version = "0.1.0"
edition = "2021"
authors = ["Kyle Gortych <kyle.gortych.dev@gmail.com>"]
description = "Declarative system package manager for NexisOS with optimized store operations and generation rollbacks"
license = "GPL-3.0-or-later"
repository = "https://github.com/NexisOS/NexisOS"
homepage = "https://github.com/NexisOS/NexisOS"
documentation = "https://github.com/NexisOS/NexisOS"
readme = "README.md"
keywords = ["package-manager", "linux", "declarative", "nixos-like", "rollback"]
categories = ["command-line-utilities", "development-tools", "os"]

[lib]
name = "nexis_pkg_mgr"
path = "src/lib.rs"

[[bin]]
name = "nexis"
path = "src/main.rs"

[dependencies]
# CLI and configuration
clap = { version = "4.4", features = ["derive", "env", "color"] }
serde = { version = "1.0", features = ["derive", "rc"] }
toml = "0.9"
config = "0.14"

# Storage backends
sled = { version = "0.34", optional = true }
rocksdb = { version = "0.22", features = ["multi-threaded-cf"], optional = true }

# Async runtime and HTTP client
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["stream", "rustls-tls"] }
futures = "0.3"

# Hashing and cryptography
sha2 = "0.10"
blake3 = "0.3"
ring = "0.17"

# Compression support
flate2 = "1.0"
tar = "0.4"
zstd = "0.13"

# File system operations
walkdir = "2.5"
tempfile = "3.10"
nix = { version = "0.29", features = ["fs"] }

# Error handling and logging
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Date/time handling
chrono = { version = "0.4", features = ["serde"] }

# Process management
subprocess = "0.2"

# JSON handling
serde_json = "1.0"

# Path manipulation and glob patterns
glob = "0.3"
pathdiff = "0.2"

# System integration
libc = "0.2"
which = "6.0"

[dev-dependencies]
tempfile = "3.10"
assert_fs = "1.1"
predicates = "3.1"
tokio-test = "0.4"

[features]
default = ["ext4-backend", "grub-integration"]

# Storage backend features
ext4-backend = ["sled"]
xfs-backend = ["rocksdb"]

# System integration features
grub-integration = []
selinux-support = []
systemd-integration = []

# Performance features
io-uring = ["tokio-uring"]
parallel-gc = []

# Development features
debug-store = []

# Optional io_uring dependency (Linux only)
[target.'cfg(target_os = "linux")'.dependencies]
tokio-uring = { version = "0.5", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
