[package]
name = "nexispm"
version = "0.1.0"
edition = "2021"
authors = ["Kyle Gortych <kyle.gortych.dev@gmail.com>"]
description = "Declarative system package manager for NexisOS with optimized store operations, refcounting, and generation rollbacks"
license = "GPL-3.0-or-later"
repository = "https://github.com/NexisOS/NexisOS"
homepage = "https://github.com/NexisOS/NexisOS"
documentation = "https://github.com/NexisOS/NexisOS"
readme = "README.md"
keywords = ["package-manager", "linux", "declarative", "nixos-like", "rollback"]
categories = ["command-line-utilities", "development-tools", "os"]

[lib]
name = "nexispm"
path = "src/lib.rs"

[[bin]]
name = "nexis"
path = "src/main.rs"

[dependencies]
# CLI and configuration
clap = { version = "4.4", features = ["derive", "env", "color"] }
serde = { version = "1.0", features = ["derive", "rc"] }
toml = "0.8"
toml_edit = { version = "0.22", optional = true }
config = { version = "0.14", optional = true }
tera = { version = "1.19", optional = true }

# Validation & diagnostics
schemars = { version = "0.8", features = ["serde"], optional = true }
serde_valid = { version = "0.15", features = ["derive"], optional = true }
miette = { version = "7", features = ["fancy"] }
thiserror = "1.0"

# Storage backend - RocksDB
rocksdb = { version = "0.22", features = ["multi-threaded-cf", "portable", "bloom"] }

# Async and networking
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "process", "io-util", "signal", "time", "net"] }
reqwest = { version = "0.12", features = ["stream", "rustls-tls", "gzip", "brotli", "hickory-dns"] }
futures = "0.3"

# Hashing and cryptography
blake3 = { version = "1", features = ["rayon"] }
xxhash-rust = { version = "0.8", features = ["xxh3"], optional = true }
ahash = { version = "0.8", optional = true }

# Merkle tree
merkle-cbt = { version = "0.3" }

# Compression and packaging
tar = "0.4"
zstd = { version = "0.13", features = ["pkg-config"] }
lz4 = { version = "1.24", optional = true }

# Filesystem
walkdir = "2.5"
tempfile = "3.10"
xattr = "1.3"
users = "0.11"
which = "6.0"
libc = "0.2"
camino = "1.1"
fs-err = "2"
notify = "6.1"
reflink-copy = { version = "0.1", optional = true }

# SELinux integration
selinux = { version = "0.4" }
selinux-sys = { version = "0.6" }

# Dinit service
ini = "1.3"

# Logging and errors
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Date/time
chrono = { version = "0.4", features = ["serde"] }

# Serialization
serde_json = "1.0"
bincode = "1"

# Performance
parking_lot = "0.12"
dashmap = { version = "5.5", optional = true }
rayon = { version = "1.10", optional = true }
crossbeam = { version = "0.8", optional = true }
bloom = { version = "0.3", optional = true }

# CLI UX
console = "0.15"
indicatif = "0.17"
dialoguer = { version = "0.11", optional = true }

# Paths and glob
glob = "0.3"
pathdiff = "0.2"

# Development
assert_fs = "1.1"
predicates = "3.1"
tokio-test = "0.4"
proptest = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }

[features]
default = [
    "desktop-profile",
    "grub-integration",
    "validation",
    "selinux-mandatory",
    "dinit-integration",
    "compression-zstd"
]

# Profiles
desktop-profile = ["rocksdb-backend", "interactive", "merkle-trees", "fast-hash"]
server-profile = ["rocksdb-backend", "system-info", "parallel-gc", "compression-fast"]

# Storage backend
rocksdb-backend = ["rocksdb"]

# Mandatory features
selinux-mandatory = ["selinux", "selinux-sys"]
dinit-integration = ["ini"]

# Compression backends
compression-zstd = ["tar", "zstd"]
compression-fast = ["lz4"]

# Integration
grub-integration = []
systemd-integration = []
layered-config = ["config", "toml_edit"]
templating = ["tera"]
validation = ["schemars", "serde_valid", "miette/fancy"]
caps-support = []
file-management = []

# Performance and system
parallel-gc = ["rayon", "bloom", "dashmap", "crossbeam"]
fast-hash = ["xxhash-rust", "ahash"]
merkle-trees = ["merkle-cbt"]
cow-copy = ["reflink-copy"]
interactive = ["dialoguer"]

# Dev/debug
extensive-logging = ["tracing-subscriber/json"]
benchmarks = []

[target.'cfg(target_os = "linux")'.dependencies]
tokio-uring = { version = "0.5", optional = true }
tikv-jemallocator = { version = "0.6", optional = true }
libselinux-sys = { version = "0.7", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-all-features]
denylist = [
    ["desktop-profile", "server-profile"],
    ["read-optimized", "write-optimized", "memory-optimized"],
    ["mimalloc-allocator", "tikv-jemallocator"],
    ["postcard", "rmp-serde"]
]

[package.metadata.nexispm.desktop-ext4-recommendations]
# Recommended directories for ext4 to maximize desktop (gaming) performance
directories = [
  "/home",
  "/var",
  "/tmp",
  "/usr/local",
  "/opt"
]

description = """
For desktop users focused on gaming performance, it is recommended to use ext4
on the following directories due to ext4's stable performance with lots of
small files, typical desktop workloads, and compatibility:

- /home : User profiles and game saves
- /var  : Variable data (logs, caches)
- /tmp  : Temporary files
- /usr/local : Locally installed software, modding tools
- /opt  : Optional third-party software and games

Other directories, such as the package store (e.g., /nexis-store), can use
XFS or another filesystem optimized for reflinks and DAG traversal to
maximize deduplication and performance for backend operations.
"""
[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
opt-level = 3

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[profile.dev]
debug = 2
overflow-checks = true
opt-level = 1

[profile.bench]
inherits = "release"
debug = true

[[bench]]
name = "store_operations"
harness = false
