version: 2
updates:
  # Root workspace Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kylegortych"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Group minor and patch updates together
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      # Group dev dependencies separately
      dev-dependencies:
        applies-to: version-updates
        dependency-type: "development"

  # Package manager specific dependencies
  - package-ecosystem: "cargo"
    directory: "/distroConfigs/packages/nexispm"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "kylegortych"
    labels:
      - "dependencies"
      - "nexispm"
      - "rust"
    commit-message:
      prefix: "deps(nexispm)"
      include: "scope"
