# Minimal NexisOS configuration example
# This demonstrates the simplest possible system configuration

[system]
hostname = "nexis-minimal"
version = "0.1.0"

[system.locale]
lang = "en_US.UTF-8"

[network]
interface = "eth0"
dhcp = true

# Essential packages for a bootable system
[[packages]]
name = "busybox"
version = "1.36.1"
source = "https://busybox.net/downloads/busybox-1.36.1.tar.bz2"
hash = "sha256:b8cc24c9574d809e7279c3be349795c5d5ceb6fdf19ca709f80cde50e47de314"
build_system = "make"

[[packages]]
name = "linux-kernel"
version = "6.6.8"
source = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.8.tar.xz"
hash = "sha256:c969dea4fb04b7392b63b4b9f6e2b8d74e929b9b3b1ccde7e80db4c2cd06c6e6"
build_system = "make"
build_flags = ["bzImage", "modules"]

# Basic service to start networking
[dinit_services.network]
name = "network"
type = "scripted" 
command = "/sbin/ifup eth0"
depends = []
