// grub.rs — Generates GRUB menu entries for NexisOS generations
//
// Adjusted for integration with rollback snapshots.

use anyhow::{Context, Result};
use log::{debug, error, info, warn};
use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

const CUSTOM_CFG: &str = "/boot/grub/custom.cfg";

/// Regenerate GRUB custom.cfg based on available Btrfs system generations.
pub fn update_grub() -> Result<()> {
    info!("Starting GRUB configuration update…");

    let root_uuid = root_uuid()?;
    debug!("Detected root UUID: {}", root_uuid);

    let mut generations = list_sys_generations()?;
    generations.sort_by_key(|p| std::cmp::Reverse(gen_id_from_path(p)));
    debug!("Found {} system generations", generations.len());

    let tmp_cfg = PathBuf::from(format!("{}.__tmp__", CUSTOM_CFG));
    let mut buf = String::from("# Autogenerated by nexpm — do not edit\n");

    for gen in &generations {
        let gen_id = gen_id_from_path(gen);
        let (kernel_rel, initrd_rel) = find_kernel_initrd(gen)?;

        if kernel_rel.is_empty() {
            warn!("Skipping generation {} — no kernel found", gen_id);
            continue;
        }

        buf.push_str(&grub_entry(gen_id, &root_uuid, &kernel_rel, &initrd_rel));
        debug!("Added GRUB menuentry for generation {}", gen_id);
    }

    if let Some(parent) = Path::new(CUSTOM_CFG).parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&tmp_cfg, buf)?;

    if !file_eq(&tmp_cfg, Path::new(CUSTOM_CFG)).unwrap_or(false) {
        info!("Updating {}", CUSTOM_CFG);
        fs::rename(&tmp_cfg, CUSTOM_CFG)?;
        let status = Command::new("grub-mkconfig")
            .args(["-o", "/boot/grub/grub.cfg"])
            .status();
        match status {
            Ok(s) if s.success() => info!("GRUB configuration regenerated successfully"),
            Ok(s) => warn!("grub-mkconfig exited with status {}", s),
            Err(e) => error!("Failed to run grub-mkconfig: {}", e),
        }
    } else {
        debug!("No changes detected in {}", CUSTOM_CFG);
        let _ = fs::remove_file(&tmp_cfg);
    }

    info!("GRUB update complete");
    Ok(())
}

/// Build a single GRUB menuentry string.
fn grub_entry(gen_id: u64, root_uuid: &str, kernel_rel: &str, initrd_rel: &str) -> String {
    let mut s = format!(
        "menuentry 'NexisOS (generation {})' {{\n",
        gen_id
    );
    s.push_str(&format!(
        "  search --no-floppy --fs-uuid --set=root {}\n",
        root_uuid
    ));
    s.push_str(&format!(
        "  linux /{} root=UUID={} rootflags=subvol=@sys-gen-{} ro quiet\n",
        kernel_rel, root_uuid, gen_id
    ));
    if !initrd_rel.is_empty() {
        s.push_str(&format!("  initrd /{}\n", initrd_rel));
    }
    s.push_str("}\n\n");
    s
}

/// List all Btrfs subvolumes matching @sys-gen-*.
fn list_sys_generations() -> Result<Vec<String>> {
    let output = Command::new("btrfs")
        .args(["subvolume", "list", "/"])
        .output()
        .context("btrfs subvolume list /")?;

    let txt = String::from_utf8_lossy(&output.stdout);
    let mut generations = Vec::new();

    for line in txt.lines() {
        if let Some(idx) = line.find("path ") {
            let rel = &line[idx + 5..];
            if rel.starts_with("@sys-gen-") {
                generations.push(format!("/{}", rel));
            }
        }
    }

    Ok(generations)
}

/// Extract generation ID from path like "/@sys-gen-42".
fn gen_id_from_path(path: &str) -> u64 {
    path.rsplit('-')
        .next()
        .and_then(|s| s.parse::<u64>().ok())
        .unwrap_or(0)
}

/// Find kernel and initrd relative paths for a generation.
fn find_kernel_initrd(sys_gen_path: &str) -> Result<(String, String)> {
    let boot_dir = Path::new(sys_gen_path).join("boot");
    if !boot_dir.exists() {
        return Ok((String::new(), String::new()));
    }

    let mut kernel = None;
    let mut initrd = None;

    if let Ok(entries) = fs::read_dir(&boot_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if let Some(fname) = path.file_name().and_then(|s| s.to_str()) {
                if fname.starts_with("vmlinuz-") {
                    kernel = Some(format!(
                        "{}/{}",
                        sys_gen_path.trim_start_matches('/'),
                        fname
                    ));
                } else if fname.starts_with("initrd") || fname.starts_with("initramfs") {
                    initrd = Some(format!(
                        "{}/{}",
                        sys_gen_path.trim_start_matches('/'),
                        fname
                    ));
                }
            }
        }
    }

    Ok((kernel.unwrap_or_default(), initrd.unwrap_or_default()))
}

/// Get root filesystem UUID.
fn root_uuid() -> Result<String> {
    let src = String::from_utf8_lossy(
        &Command::new("findmnt")
            .args(["-no", "SOURCE", "/"])
            .output()
            .context("findmnt /")?
            .stdout,
    )
    .trim()
    .to_string();

    let uuid = String::from_utf8_lossy(
        &Command::new("blkid")
            .args(["-s", "UUID", "-o", "value", &src])
            .output()
            .context("blkid root")?
            .stdout,
    )
    .trim()
    .to_string();

    if uuid.is_empty() {
        anyhow::bail!("could not determine root UUID");
    }
    Ok(uuid)
}

/// Compare two files by contents.
fn file_eq(a: &Path, b: &Path) -> Result<bool> {
    if !a.exists() || !b.exists() {
        return Ok(false);
    }
    Ok(fs::read(a)? == fs::read(b)?)
}
